
sudo: false

language: php

script:
  - php -v

cache:
  directories:
    - "$HOME/.composer/cache"

before_deploy:
  - echo 'start'
  - composer self-update
  - composer install --no-dev --no-interaction --ignore-platform-reqs
  - zip -r --exclude='*.git*' --exclude='*.zip' --exclude='*.travis.yml' DuxCMS_FULL.zip .
  - git diff ac8c7e4 $(git tag | awk "END{print}") --name-only | xargs zip DuxCMS_UPDATE.zip

deploy:
  provider: releases
  api_key:
    secure: Bg3ZAtBWY4/Kpk9I7UYNevOyEQWL/Q9mHLltqvDmMN9iBBL/QAzpbk6fwg0D2HHfNW6VfKlURKm7WlBG3xctEfoX6ULaT5IMfLoBD8J8aMhs3t5BWTxxkbVb8LJvRmcDwEKOHioaFofUlRU26mVAhrsSCNMXf+6iV0HVk1UaZTpOujUQs+yr2mtn68te0HTL45Ja2m830ZVKwj0JKv0glmoicvpT4xnY7V80iUgX6w8CE40DkX7rI9hMNXjVoDTp+vcEeEyFCeQGaXBiUqHVrtj1CVum9E2PVn3v7DRz/O89wsWQJ17lnRBR/IjNsCVZJI3Fvx17JQNOMZuPD2NfyQ60bjK6VwgnxSgQ82VknrWidanUJQo5BVtoO4xM115mxsWUgRSQP5mNwicx5Mo36fYsxjOhgIwC1qAJQ/0C4/8fpM81mPqAmMPsbR8ETlJ9MHk5wPUFqy8S6KdHCIxxvGecLAVQOPPBhHY6F26flXx83AlE3I/z3lEd+k18JQ6Ac1luYf6nsVHOSs2fA6V9qLuIpue6B3icXsdVtDOy77ke7i6/iJYo2X7ep0fqJ/V87d9IPwrdXN6J3bYqg7cKoKjSUEDAkFO4ZjPQAi8LzYQYWSd9eDCYwU2aj6IivTIfcE6yjCQ98IGgcz+Nz3PTBr7Yxkid47a55bP7gjzqJGw=
  file: 
    - /home/travis/build/edenleung/duxcms-2.1/DuxCMS_FULL.zip
    - /home/travis/build/edenleung/duxcms-2.1/DuxCMS_UPDATE.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
